### ISSUE TITLE
关于Rabbit的疑问

### ISSUE THREAD

**Issue by keeleys** [pzxwhc/MineKnowContainer#72]
如果吧生产者和消费者分开成2个项目的话
消息绑定QueueBinding（是在哪边定义呢。）

**Comment by waterlang** [comment]
@ keeleys  正常生产者（一般是服务端）只负责Exchange及key的定义，Queue及binding操作在client端。当然如果你的server端须要操作到queue也可以定义，比如我的server端须要收到client处理消息的结果时就须要在server端单独定义一个queue。

**Comment by keeleys** [comment]
3q

**Comment by pzxwhc** [comment]
@keeleys @waterlang 不好意思，一直没回。我们目前具体的应用上是由rabbitmq 提供的操作界面来配置，没有通过代码相绑定起来。这样子有个好处就是我们有时候改动rabbitmq的时候不需要改代码。
