### ISSUE TITLE
RabbitHandler注解的使用

### ISSUE THREAD

**Issue by yosaku01** [pzxwhc/MineKnowContainer#83]
你RabbitHandler注解的使用仍然是String类型的消息体
你试过POJO类型的消息么？
RabbitHandler提到的就是可以处理不同消息类型的消息体，可你的例子里没有反映出来。

**Comment by pzxwhc** [comment]
@yosaku01 可以看下 本 repository 的 rabbitmq 文件夹的 demo，已经重新整理了。另外，RabbitHandler提到的就是可以处理不同消息类型的消息体本质上是要配置 ***消息转换器***，因为默认的消息转换器只会转成  String 类型，就是你提到的 String 类型的消息体，但是如果配置有像 Jackson2JsonMessageConverter 这种类型的，那么就可以转化成固定的类。

**Comment by yosaku01** [comment]
你这个方法还有两个问题:
1)你添加的MessageConverter只对应了一个Student类对象，如果我的消息类型有多种类型怎么处理？
2)使用RabbitTemplate.convertAndSend方法发送对象有一个问题，就是不能定制MessageProperties,
例如我不同类型的对象，要求处理后消息返回队列(replyTo)不一样，不能统一在RabbitTemplate中进行设定。
我现在的解决方法没有使用convertAndSend方法，仍然使用RabbitTemplate.send方法，只是将MessageProperties的content-type设置为application/x-java-serialized-object，在使用MessageBuilder构建对象时将对象序列化成byte流，作为消息体。
在消费者一侧，只需要使用SimpleMessageConverter就可以将消息体反序列化为实际对象，不需要再添加
ClassMapper了。
3)如果你要发送对象消息，也可以直接使用RabbitMessagingTemplate类，直接在这个类中设置MessageConverter，再使用它的ConvertAndSend方法发送消息。

**Comment by pzxwhc** [comment]
@yosaku01 上传了最新的 rabbitmq 代码，支持多种类型。原理上来说，它会加入一个请求头, key 是 `__TypeId__`， value 是你设置的类，例如我设置的 `Student`（你可以在 rabbitmq 的 界面上看看这个消息，是有这个 header 的）。那么在接受的时候，接收方就会根据这个请求头，找到对应的 Student 类，再用 Jackson2JsonMessageConverter 进行转换。

在我的那个代码里面，在 RabbitMQConfig 类中，我定义了两个转换器，可能你会有点疑惑，这个是在模拟发送方和接收方的 Student 不是同一个。

MessageProperties 也不能说不能定义，只是实现起来有点麻烦，需要你定义自己的 转换器，然后实现 toMessage 这些方法，RabbitTemplate  的 convertAndSend 方法会 `new MessageProperties()` 传给你，然后你不要就可以了，用自己的。 不过总的来说是有点麻烦。

另外，你说的

> 例如我不同类型的对象，要求处理后消息返回队列(replyTo)不一样  

这个是什么意思

**Comment by yosaku01** [comment]
另外，你说的
**例如我不同类型的对象，要求处理后消息返回队列(replyTo)不一样**
这个是什么意思

我的意思是说，如果我发送的RabbitMQ消息对象类型不一致，可能代表不同的业务需求
要求消费者端处理后将返回消息发送到不同的返回队列里。
RabbitTemplate只能定义一个replyAddress，不能满足这个要求。
因此我想在发送消息时，在附带的MessageProperties里提供replyTo 返回队列(Exchange)信息，便于消费者端发送返回消息。

在我的那个代码里面，在 RabbitMQConfig 类中，我定义了两个转换器，可能你会有点疑惑，这个是在模拟发送方和接收方的 Student 不是同一个。
我在看自定义handlerMethodFactory时可以定义一个MessageConverterCollection，我想是否可以通过它实现对不同类型对象消息的转换？
